name: Check
run-name: Check

on:
  push:
  workflow_dispatch:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install flake8
        run: pip3 install flake8

      - name: Checking
        run: flake8 weekly4note.py
