name: Lint check
run-name: Lint check

on:
  push:
  workflow_dispatch:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install flake8
        run: pip3 install flake8

      - name: Show current path.
        run: pwd

      - name: Show other directiry.
        run: tree ../

      # - name: Checking
      #   run: flake8 gen_weekly_todo.py
